#!/bin/sh
echo "Launching ElectrumZ server..."
USERNAME=$(envdir ./env printenv USERNAME)
ELECTRUMZ=$(envdir ./env printenv ELECTRUMZ)
ulimit -n 4000 && exec 2>&1 envdir ./env envuidgid $USERNAME python3 $ELECTRUMZ
